name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd pillowpon_backend || git clone https://github.com/welcome-kaist/pillowpon_backend.git pillowpon_backend && cd pillowpon_backend
            git pull origin main
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.dev
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.dev
            docker build -t pillowpon-backend .
            docker stop pillowpon-backend || true && docker rm pillowpon-backend || true
            docker run -d \
              --name pillowpon-backend \
              --env-file .env.dev \
              -p 3000:3000 \
              pillowpon-backend
          EOF
