name: Deploy to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_IMAGE }}

      - name: Deploy to EC2 via SSH and Docker
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop pillowpon-backend || true
            docker rm pillowpon-backend || true
            docker pull ${{ secrets.DOCKER_IMAGE }}
            docker run -d \
              --name pillowpon-backend \
              --env-file .env.dev \
              -p 3000:3000 \
              ${{ secrets.DOCKER_IMAGE }}
          EOF
